version: 0.2

env:
  variables:
    SOLUTION: .\PlanITImpact-Core.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.1
    PROJECT1: PlanItImpact.Data
    PROJECT2: PlanItImpact.Core
phases:
  build:
    commands:
      - echo $env
      - nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY
      - msbuild $env:SOLUTION /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release
artifacts:
  files:
    - .\PlanITImpact.Data\bin\Release\*
    - .\PlanITImpact.Core\bin\Release\*
