version: 0.2
phases:
  build:
    commands:
      - choco install visualstudio2017professional -y --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --includeOptional --passive --norestart --wait --locale=en-US
      - choco list
    finally:
      - '& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
      - type C:\ProgramData\chocolatey\logs\chocolatey.log
      - echo "End of 'finally' block"
